services:
  authserver:
    image: ${DOCKER_USER}/authserver:latest
    build: 
      context: .
      dockerfile: ./services/authserver/Dockerfile
  
  systemserver:
    image: ${DOCKER_USER}/systemserver:latest
    build: 
      context: .
      dockerfile: ./services/systemserver/Dockerfile

  chatsocketserver:
    image: ${DOCKER_USER}/chatsocketserver:latest
    build: 
      context: .
      dockerfile: ./services/chatsocketserver/Dockerfile
  
  oauthserver:
    image: ${DOCKER_USER}/oauthserver:latest
    build: 
      context: .
      dockerfile: ./services/oauthserver/Dockerfile
  
  userserver:
    image: ${DOCKER_USER}/userserver:latest
    build: 
      context: .
      dockerfile: ./services/userserver/Dockerfile
  
  workerservice:
    image: ${DOCKER_USER}/workerservice:latest
    build: 
      context: .
      dockerfile: ./services/workerservice/Dockerfile