services:
  authserver:
    container_name: glam_auth_server
    image: ${DOCKER_USER}/authserver:latest
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      SWAGGER_URL: ${SWAGGER_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      OTP_TIMEOUT: ${OTP_TIMEOUT}
      OTP_MAXSIZE: ${OTP_MAXSIZE}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}


    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks
      
  systemserver:
    container_name: glam_system_server
    image: ${DOCKER_USER}/systemserver:latest
    restart: always
    environment:
      environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      SWAGGER_URL: ${SWAGGER_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks

  chatsocketserver:
    container_name: glam_chatsocket_server 
    restart: always
    image: ${DOCKER_USER}/chatsocketserver:latest
    environment:
      environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      SWAGGER_URL: ${SWAGGER_URL}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks
  
  oauthserver:
    container_name: glam_oauth_server
    restart: always
    image: ${DOCKER_USER}/oauthserver:latest
    environment:
      environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      SWAGGER_URL: ${SWAGGER_URL}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks
  
  userserver:
    container_name: glam_user_server
    restart: always
    image: ${DOCKER_USER}/userserver:latest
    environment:
      environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      SWAGGER_URL: ${SWAGGER_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks
  
  workerservice:
    container_name: glam_worker_service
    image: ${DOCKER_USER}/workerservice:latest
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      BUCKET: ${BUCKET}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks

  nailserver:
    container_name: glam_nail_server
    image: ${DOCKER_USER}/nailserver:latest
    restart: always
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PENV: ${PENV}
      PORT: ${PORT}
      BASE_URL_API: ${BASE_URL_API}
      ORIGIN_ALLOWED: ${ORIGIN_ALLOWED}
      ACCESS_TOKEN_EXT: ${ACCESS_TOKEN_EXT}
      ACCESS_TOKEN_KEY: ${ACCESS_TOKEN_KEY}
      REFRESH_TOKEN_EXT: ${REFRESH_TOKEN_EXT}
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      SWAGGER_URL: ${SWAGGER_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_PORT: ${MAIL_PORT}
      OTP_TIMEOUT: ${OTP_TIMEOUT}
      OTP_MAXSIZE: ${OTP_MAXSIZE}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - ${DEPLOY_PORT}:${PORT}
    networks:
      - glam-networks

networks:
  glam-networks:
    name: glam_networks
    external: true