spring:
    application:
      name: glam oauth server
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
    flyway:
        baselineOnMigrate: true

server:
    servlet:
        context-path: /api/v1
    port: ${PORT}

security:
    client:
        id: ${CLIENT_DEFAULT_ID:glam-client}
        secret: ${SECRET_DEFAULT_ID:123456789}
        redirect-urls: http://localhost:3000,http://localhost:9000