spring:
    application:
      name: glam authentication server
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
    
    profiles:
        active: ${PENV}
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
                         


server:
    servlet:
        context-path: /api/v1
    port: ${PORT}

springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        try-it-out-enabled: true
        operations-sorter: method
        tags-sorter: alpha
        filter: true
        path: /swagger-ui

base-urls:
    api: ${BASE_URL_API:null}
    front-end: ${ORIGIN_ALLOWED:null}
access-token:
    max-age: ${ACCESS_TOKEN_EXT:86400000}
    secret-key: ${ACCESS_TOKEN_KEY}

refresh-token:
    max-age: ${REFRESH_TOKEN_EXT:315360000}
    secret-key: ${REFRESH_TOKEN_KEY}

swagger-url: ${SWAGGER_URL:null}

vnp:
    pay-url: ${VNP_PAYURL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    return-url: ${VNP_RETURN_URL:/api/v1/payments/vnpay-payment}
    tmn-code: ${VNP_TMN_CODE}
    hash-secret: ${VNP_HASH_SECRET}
    api-url: ${VNP_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}