spring:
    application:
      name: glam user server
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
    
    profiles:
        active: ${PENV}
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB

server:
    servlet:
        context-path: /api/v1
    port: ${PORT}

base-urls:
    api: ${BASE_URL_API:null}
    front-end: ${ORIGIN_ALLOWED:null}


springdoc:
    api-docs:
        enabled: true
        path: /api-docs
    swagger-ui:
        enabled: true
        try-it-out-enabled: true
        operations-sorter: method
        tags-sorter: alpha
        filter: true
        path: /swagger-ui

swagger-url: ${SWAGGER_URL:null}

aws:
    s3:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
        region: ${AWS_REGION}
        endpoint: ${AWS_ENDPOINT}
        bucket: ${BUCKET}
