spring:
    application:
      name: glam user server
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.import org.springframework.security.oauth2.server.authorization.settings.ClientSettings;naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://${AUTH_HOST}:${AUTH_PORT}


server:
    servlet:
        context-path: /api/v1
    port: ${PORT}