run-name: ${{inputs.service}} docker build image
on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      infisical_token:
        type: string
        required: true
    secrets:
      DOCKER_USERNAME:
      INFISICAL_URL:
      INFISICAL_PROJECT_ID:
      DOCKER_PASSWORD:
jobs:
  build-image:
    name: API Image Build
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3
      - name: Debug Output
        run: |
          echo "Infisical Token: ${{ inputs.infisical_token }}"

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Image And Push
        run: docker compose build ${{inputs.service}} && docker compose push ${{inputs.service}}
  
  deploy-service:
    uses: ./.github/workflows/deploy.yaml
    needs: ['build-image']
    with:
      server: arisa-server
      infisical-token: ${{inputs.infisical_token}}
      service: ${{inputs.service}}
    secrets: 
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      INFISICAL_URL: ${{secrets.INFISICAL_URL}}
      INFISICAL_PROJECT_ID: ${{secrets.INFISICAL_PROJECT_ID}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
