on: 
    push:   
      branches: 
        - main
      paths: 
        - 'services/**'
        - 'packages/**'
    workflow_dispatch: 
jobs:
  glam-deploy-serve-cd:
    name: glam-deploy-serve-cd
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        service: [
          "authserver",
          "userserver",
          "chatsocketserver",
          "systemserver",
          "workerservice",
          "nailserver",
          "oauthserver",
        ]
      fail-fast: false
    with:
      service: ${{matrix.service}}
    secrets: 
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      INFISICAL_URL: ${{secrets.INFISICAL_URL}}
      INFISICAL_PROJECT_ID: ${{secrets.INFISICAL_PROJECT_ID}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      INFISICAL_CLIENT_ID: ${{secrets.INFISICAL_CLIENT_ID}}
      INFISICAL_CLIENT_SECRET: ${{secrets.INFISICAL_CLIENT_SECRET}}
    
      
