on: 
    push:   
      branches: 
        - main
      paths: 
        - 'services/**'
        - 'packages/**'
    workflow_dispatch: 
jobs:
  
  glam-infisical-login:
    name: glam-infisical-login
    runs-on: arisa-server
    outputs:
      infisical_token: ${{steps.infisical-login.token}}
    steps:
      - name: Infisical Login
        id: infisical-login
        run: |
          INFISICAL_TOKEN=$(infisical login --domain=${{ secrets.INFISICAL_URL }} --method=universal-auth --client-id=${{ secrets.INFISICAL_CLIENT_ID }} --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }} --silent --plain)
          echo "INFISICAL_TOKEN=$INFISICAL_TOKEN" >> $GITHUB_ENV
          echo "::set-output name=token::$INFISICAL_TOKEN"
  
  glam-check-change:
    runs-on: ubuntu-latest
    needs: glam-infisical-login
    outputs:
      services: ${{steps.set-output.outputs.services}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check change
        uses: dorny/paths-filter@v2
        id: filter
        with:
          initial-fetch-depth: 2
          filters: |
            authserver:
              - 'services/authserver/**'
            userserver:
              - 'services/userserver/**'
            chatsocketserver:
              - 'services/chatsocketserver/**'
            systemserver:
              - 'services/systemserver/**'
            workerservice:
              - 'services/workerservice/**'
            nailserver:
              - 'services/nailserver/**'
            oauthserver:
              - 'services/oauthserver/**'
      - name: Set services output
        id: set-output
        run: |
          echo "::set-output name=services::$(echo '${{ toJson(steps.filter.outputs) }}' | jq -r 'to_entries | map(select(.value == "true") | .key) | join(",")') )"
      

  glam-deploy-cd:
    name: glam-deploy-cd
    uses: ./.github/workflows/build.yaml
    with:
      service: ${{fromJson(needs.glam-check-change.outputs.services)}}
      infisical_token: ${{needs.glam-infisical-login.outputs.infisical_token}}
    needs: [glam-infisical-login,glam-check-change]
    strategy:
      matrix:
        service: ${{needs.glam-check-change.outputs.services}}
      max-parallel: 5
      fail-fast: false
    
      
