on: 
    push:   
      branches: 
        - main
      paths: 
        - 'services/**'
        - 'packages/**'
    workflow_dispatch: 
jobs:
  
  glam-infisical-login:
    name: glam-infisical-login
    runs-on: arisa-server
    outputs:
      infisical_token: ${{steps.infisical-login.outputs.infisical_token}}
    steps:
      - name: Infisical Login
        id: infisical-login
        run: |
          echo "infisical_token=$(infisical login --domain=${{secrets.INFISICAL_URL}} --method=universal-auth --client-id=${{secrets.INFISICAL_CLIENT_ID}} --client-secret=${{secrets.INFISICAL_CLIENT_SECRET}} --silent --plain)" >> "$GITHUB_OUTPUT"
      

  glam-deploy-serve-cd:
    name: glam-deploy-serve-cd
    needs: [glam-infisical-login]
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        service: [
          "authserver",
          "userserver",
          "chatsocketserver",
          "systemserver",
          "workerservice",
          "nailserver",
          "oauthserver",
        ]
      fail-fast: false
    with:
      infisical_token: ${{needs.glam-infisical-login.outputs.infisical_token}}
      service: ${{matrix.service}}
    secrets: 
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      INFISICAL_URL: ${{secrets.INFISICAL_URL}}
      INFISICAL_PROJECT_ID: ${{secrets.INFISICAL_PROJECT_ID}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    
      
