on: 
    push:   
      branches: 
        - main
      paths: 
        - 'services/**'
        - 'packages/**'
    workflow_dispatch: 
jobs:
  
  glam-infisical-login:
    name: glam-infisical-login
    runs-on: arisa-server
    outputs:
      infisical_token: ${{env.INFISICAL_TOKEN}}
    steps:
      - name: Infisical Login
        id: infisical-login
        run: |
          INFISICAL_TOKEN=$(infisical login --domain=${{ secrets.INFISICAL_URL }} --method=universal-auth --client-id=${{ secrets.INFISICAL_CLIENT_ID }} --client-secret=${{ secrets.INFISICAL_CLIENT_SECRET }} --silent --plain)
          echo "INFISICAL_TOKEN=$INFISICAL_TOKEN" >> $GITHUB_ENV
  
  glam-check-change:
    runs-on: ubuntu-latest
    needs: glam-infisical-login
    outputs:
      services: ${{steps.filter.outputs}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: check change
        uses: dorny/paths-filter@v3
        id: filter
        with:
          initial-fetch-depth: 2
          filters: |
            authserver:
              - 'services/authserver/**'
            userserver:
              - 'services/userserver/**'
            chatsocketserver:
              - 'services/chatsocketserver/**'
            systemserver:
              - 'services/systemserver/**'
            workerservice:
              - 'services/workerservice/**'
            nailserver:
              - 'services/nailserver/**'
            oauthserver:
              - 'services/oauthserver/**'
      

  glam-deploy-serve-cd:
    name: glam-deploy-serve-cd
    needs: [glam-check-change,glam-infisical-login]
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        service: [
          "authserver",
          "userserver",
          "chatsocketserver",
          "systemserver",
          "workerservice",
          "nailserver",
          "oauthserver",
        ]
    with:
      infisical_token: ${{needs.glam-infisical-login.outputs.infisical_token}}
      service: ${{matrix.service}}
      change-service: ${{fromJson(needs.glam-check-change.outputs.services)}}
    
      
